# Generated by Django 5.0 on 2024-02-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feed',
        ),
        migrations.AlterModelTable(
            name='feed',
            table='feed',
        ),
    ]
